# SPDX-FileCopyrightText: 2025 Knitli Inc. <knitli@knit.li>
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
version: 2
updates:
  - package-ecosystem: cargo
    dependency-type: all
    update-types:
      - version-update:semver-minor
      - version-update:semver-patch
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: daily
      time: "23:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    assignees:
      - codegen-sh[bot]
    reviewers:
      - codegen-sh[bot]
    labels:
      - "dependencies"
    rebase-strategy: auto
  - package-ecosystem: github-actions
    dependency-type: all
    update-types:
      - version-update:semver-major
      - version-update:semver-minor
      - version-update:semver-patch
    versioning-strategy: increase
    directory: "/.github/workflows"
    schedule:
      interval: daily
      time: "23:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    assignees:
      - codegen-sh[bot]
    reviewers:
      - codegen-sh[bot]
    labels:
      - "dependencies"
    rebase-strategy: auto
