# SPDX-FileCopyrightText: 2025 Knitli Inc. <knitli@knit.li>
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
[default]
locale = "en-us"
check-file = true
check-filename = true
extend-ignore-re = ["(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on"]
extend-ignore-identifiers-re = [
  "iif",
  "iife",
  "i18n",
  "i18next",
  "i18n-t",
  "i18n-tc",
  "strat",
  "Inferrable",
]

[files]
ignore-hidden = false
ignore-files = true
extend-exclude = [
  "/usr/**/*",
  "/tmp/**/*",
  "/**/node_modules/**",
  "node_modules",
  "mkdocs-material",
  "license-list-data",
  "external",
  "vendor",
  ".git",
  "/usr/share/code/**/*",
  "eslint.config.mjs",
  "docs/manifest.json",
  "src/assets/videos/**/*",
  "src/assets/fonts/**/*",
  "src/assets/images/**/*",
]
