# SPDX-FileCopyrightText: 2025 Knitli Inc. <knitli@knit.li>
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# dashmap = { version = "6.1.0", features = ["rayon", "inline"] }
# fmmap = { version = "0.4.0", features = ["tokio"] } # memory map for handling large files efficiently
# ignore = { version = "0.4.23", features = ["simd-accel"] } # gitignore
# rapidhash = { version = "1.4.0", features = ["std"] } # fast hashing for content addressing
# rayon = { version = "1.10.0", features = ["std"] }
# ropey = "1.6.1"
# serde = { version = "1.0.219", features = ["derive"] }
# serde_json = "1.0.140"

# tokio = { version = "1.46.0", features = ["fs", "io-std", "io-util"], default-features = false}
# zerocopy = { version = "0.8.26", features = ["alloc", "simd"] }
# zerocopy-derive = "0.8.26" # included in zerocopy but separated for faster compilation
