[package]
name = "ag-service-scan"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Single-function scan_files crate for AST-grep. MIT licensed."

[dependencies]
ag-service-types.workspace = true
ag-service-core.workspace = true
ag_service_rule.workspace = true
thread_languages.workspace = true
