# SPDX-FileCopyrightText: 2025 Knitli Inc. <knitli@knit.li>
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "thread-rule-engine"
description = "Rule-based scanning and transformation engine for Thread"
keywords = ["ast", "pattern", "codemod", "search", "rewrite", "rules"]
version = "0.1.0"
license = "AGPL-3.0-or-later AND MIT"
authors = [
  "Herrington Darkholme <2883231+HerringtonDarkholme@users.noreply.github.com>",
  "Knitli Inc <knitli@knit.li>",
  "Adam Poulemanos for Knitli <adam@knit.li>",
]
edition.workspace = true
repository.workspace = true
rust-version.workspace = true
include.workspace = true

[features]
default = ["scanning", "fixing"]
# The 'scanning' feature enables finding code via rules
scanning = ["thread-ast-engine/matching"]
# The 'fixing' feature enables transforming code via rules
fixing = ["thread-ast-engine/matching"]

[dependencies]
thread-ast-engine = { workspace = true, default-features = false }
thread-utils = { workspace = true, default-features = false, features = ["hashers", "simd"] }
bit-set.workspace = true
globset = "0.4.16"
regex.workspace = true
serde.workspace = true
serde_yaml = { workspace = true }
serde_json = { workspace = true }
thiserror.workspace = true
schemars.workspace = true

[dev-dependencies]
tree-sitter-typescript = "0.23.2"
